# .github/workflows/terraform.yml

name: Terraform Plan and Apply with Approval

on:
  push:
    # paths:
    #   - 'terraform/**'  # Trigger only if changes are in the terraform folder

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform  # Set the default working directory for all run steps
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan -no-color

      - name: Print Terraform Plan
        run: terraform show -no-color tfplan

      - name: Wait for Approval
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/github-script@v6
        with:
          script: |
            const { data: { html_url } } = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'terraform.yml',
              ref: 'main',
              inputs: {
                approve: 'true'
              }
            });
            console.log(`Please approve the plan at: ${html_url}`);

      - name: Terraform Apply
        if: github.event.inputs.approve == 'true'
        run: terraform apply -auto-approve tfplan
